# Site settings
title: Lens
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a> with Instagram images loaded using <a href="https://profilepageimages.usecue.com">PPI</a>.
baseurl: '/lens-jekyll-theme' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

# Plugins
# https://github.com/brockfanning/jekyll-get-json
# Note that as of 2021-06-11 Github Pages does not support 3rd party plugins.
# Automated workaround: http://joshfrankel.me/blog/deploying-a-jekyll-blog-to-github-pages-with-custom-plugins-and-travisci/
plugins:
  - jekyll-get-json

# Get JSON data
# Replace PPI json url with the one with your username
jekyll_get_json:
  - data: images
    json: 'https://profilepageimages.usecue.com/images/paigebydj/images.json'
